

export const ServiceCategories = [
    'Vessel Management & Administration',
    'Maritime Legal & Compliance Assistance',
    'Crew Recruitment & Placement Services',
    'Customs & Immigration Assistance',
    'Insurance & Risk Management',
    'Security & Anti-Piracy Training',
    'Safety Equipment Inspections & Compliance',
    'IT & Cybersecurity Services for Yachts',
    'Charter & Itinerary Planning Assistance',
    'Satellite & Internet Connectivity Solutions',
    'Fresh Produce & Gourmet Food Provisioning',
    'Butcher & Seafood Supply Services',
    'Specialty Ingredient Sourcing',
    'Custom Catering & Onboard Chef Services',
    'Galley Equipment Maintenance & Repair',
    'Wine, Spirits & Specialty Beverages Supply',
    'Specialty Coffee & Tea Provisioning',
    'Dry & Frozen Goods Supply',
    'Galley Deep Cleaning & Sanitation Services',
    'Kitchenware & Culinary Equipment Supply',
    'Marine Engine Servicing & Repairs',
    'Generator Installation & Maintenance',
    'HVAC & Refrigeration Services',
    'Watermaker Installation & Repairs',
    'Fuel System Cleaning & Maintenance',
    'Electrical System Troubleshooting',
    'Navigation & Communication System Setup',
    'Hydraulic System Servicing',
    'Welding & Metal Fabrication Services',
    'Spare Parts Sourcing & Logistics',
    'Yacht Interior Cleaning & Housekeeping',
    'Laundry & Dry Cleaning Services',
    'Custom Interior Design & Refurbishment',
    'Florist & Fresh Flower Arrangements',
    'Carpet & Upholstery Cleaning',
    'Event & Party Planning Services',
    'Provisioning for Guest Supplies',
    'Bar & Beverage Supply Services',
    'AV & Entertainment System Installation',
    'Crew Uniform Tailoring & Embroidery',
    'Yacht Detailing & Washdowns',
    'Teak Deck Sanding & Restoration',
    'Varnishing & Paintwork Services',
    'Fiberglass & Gelcoat Repairs',
    'Docking & Line Handling Assistance',
    'Diving & Underwater Hull Cleaning',
    'Fender & Rope Supply & Maintenance',
    'Tender & Jet Ski Servicing',
    'Watersports Equipment Rental & Repairs',
    'Exterior Upholstery & Canvas Work',
    'Mental Health Support',
    'Confidential Therapy',
    'Career Guidance',
    'Legal Consultation',
    'Financial Advisory',
]